/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TheBills;

import java.util.List;

import net.dean.jraw.RedditClient;
import net.dean.jraw.http.UserAgent;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        RedditConnect.setUp();
        TTSHelper.resolveText("DUPA");
        List<Post> dupa = RedditHelper.getPosts("RocketLeague");
        for (Post post : dupa) {
            System.out.println(post);
        }
        Window XD = new Window();

    }
}
